### ISSUE TITLE
FR: Support for PostgreSQL

### ISSUE THREAD

**Issue by craft37** [locomotivecms/engine#1111] opened 2016-01-13 17:50 UTC
Subj.

**Comment by did** [comment] 2016-01-13 21:24
duplicate of #381

**Comment by did** [comment] 2016-01-13 21:27
@craft37. Supporting PostgreSQL is definitively possible but represents a **huge** work, too big for our current team. Right now, we prefer to add new features. 
Perhaps with a bigger team (people with a lot of commitment), we could handle that.

**Comment by craft37** [comment] 2016-01-15 09:40
At least we reopened this question for future.
Case inspired by this articles:
http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/
https://news.ycombinator.com/item?id=9912842

**Closed** 2016-11-25 00:35 UTC
Labels: feature

**Comment by wafcio** [comment] 2018-07-17 21:54
@did: I have found way how to add support for PostgreSQL in LocomotiveCMS. I know that it isn't your important goal but if I think many people will be happy about it. I have worked in one project where we migrated from one ORM to another so I have some experience in this.

Before add support for PostgreSQL (ActiveRecord) it will be good to make some changes which should help. I have made some changes for Locomotive::Account here: https://github.com/locomotivecms/engine/compare/master...alterans:better-tests-coverage-for-account, so let me know what do you think about it.

If you are open for this idea let me know and we can talk more about it on gitter or different issue.

**Comment by did** [comment] 2018-07-18 07:50
hi @wafcio!, that's really good stuff! Thanks!
Actually, migrating to Postgresql is scheduled for this year thanks to these awesome guys: https://github.com/akretion (@sebastienbeau)
The task still remains huge because we've got to refactor the custom_fields gem and also add a PG adapter for the steam gem. 
Let's talk about it on Gitter this week!
