### ISSUE TITLE
Feature: Administration: Gridview for ContentEntries

### ISSUE THREAD

**Issue by paulsponagl** [locomotivecms/engine#370] opened 2012-04-18 08:51 UTC
If a user clicks on the ContentType now a List appears where the user is able to sort or click "Edit/Destroy"

I think it would be great having a Gridview as an Option that allows us to edit/modify the previously marked 
fields inplace.

We could use
https://github.com/mleibman/SlickGrid
for this. 

Additional a split view would be nice - clicking on the row opens the complete form to edit below the grid.

Comments? Suggestions ?

**Comment by did** [comment] 2019-04-05 15:40
duplicate of #1253

**Closed by did** 2019-04-05 15:40 UTC
Labels: feature
